spring:
  application:
    name: business
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://143.198.83.9:5431/service
    username: soknem
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


