
spring:
  application:
    name: config-server
  profiles:
    active: native,git,dev
  cloud:
    config:
      enabled: true
      server:
        git:
          search-paths: /**
          uri: https://github.com/soknem/yelp-config-resource.git
          default-label: main
          clone-on-start: true
  kafka:
    bootstrap-servers:
      - http://143.198.83.9:9092

#  cloud:
#    config:
#      server:
#        native:
#          search-locations:
#            - file:///D:/CSTAD ADVANCE/yelp-config/
#            - file:///D:/CSTAD ADVANCE/yelp-config/{application}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888
logging:
  level:
    org.springframework.cloud.config: DEBUG