spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:///D:/CSTAD ADVANCE/yelp-config/
            - file:///D:/CSTAD ADVANCE/yelp-config/{application}
